name: Go

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install
        run: go get github.com/mitchellh/gox

      - name: Build
        run: $(go env GOPATH)/bin/gox
          -osarch='darwin/amd64 linux/amd64 linux/386 freebsd/amd64 freebsd/386'
          -output=dist/{{.Dir}}_{{.OS}}_{{.Arch}}
          -ldflags='-X main.version=0.0.0+${{ github.sha }}'
          ./...

      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
